name: Laravel CI with MySQL

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, tokenizer, gd
        coverage: xdebug

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel_test" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate application key
      run: php artisan key:generate

    - name: Wait for MySQL to be ready
      run: |
        sudo apt-get install -y netcat
        echo "Waiting for MySQL to be ready..."
        while ! nc -z 127.0.0.1 3306; do
          sleep 2
        done
        echo "MySQL is ready!"

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test